package helpers

func CompanyNames() []string{
    arr1 := readCompanyNamesFromCSV();
    arr2 := []string {}
    // arr2 := []string{
    //     "Amazon",
    //     "Microsoft",
    //     "Google",
    //     "Apple",
    //     "IBM",
    //     "Intel",
    //     "Cisco",
    //     "Oracle",
    //     "HewlettPackard",
    //     "Dell",
    //     "Salesforce",
    //     "Adobe",
    //     "VMware",
    //     "NetApp",
    //     "RedHat",
    //     "Symantec",
    //     "Akamai",
    //     "Qualcomm",
    //     "Broadcom",
    //     "NVIDIA",
    //     "Meta",
    //     "Facebook",
    //     "Twitter",
    //     "LinkedIn",
    //     "Uber",
    //     "Airbnb",
    //     "Dropbox",
    //     "Slack",
    //     "GitHub",
    //     "Zendesk",
    //     "Box",
    //     "Square",
    //     "PagerDuty",
    //     "Okta",
    //     "Twilio",
    //     "DocuSign",
    //     "Atlassian",
    //     "MongoDB",
    //     "Splunk",
    //     "Cloudera",
    //     "Fortinet",
    //     "Palo Alto",
    //     "FireEye",
    //     "Proofpoint",
    //     "Carbon",
    //     "Rapid7",
    //     "CrowdStrike",
    //     "Tanium",
    //     "Zscaler",
    //     "Netskope",
    //     "Okta",
    //     "Ping",
    //     "Centrify",
    //     "Varonis",
    //     "Imperva",
    //     "F5",
    //     "Citrix",
    //     "Juniper",
    //     "VMware",
    //     "Qualys",
    //     "ServiceNow",
    //     "Alphabet",
    //     "Tesla",
    //     "Netflix",
    //     "PayPal",
    //     "Square",
    //     "GoDaddy",
    //     "DocuSign",
    //     "Atlassian",
    //     "Twilio",
    //     "Zoom",
    //     "DocuSign",
    //     "DocuWare",
    //     "Dynatrace",
    //     "Dynavax",
    //     "Dynetics",
    //     "DynoSense",
    //     "Edifecs",
    //     "eGain",
    //     "Electric",
    //     "Eliassen",
    //     "Ellie",
    //     "Ellucian",
    //     "EMC",
    //     "Emulex",
    //     "Endgame",
    //     "EnerNOC",
    //     "Enphase",
    //     "Entegris",
    //     "Entrust",
    //     "Epic Games",
    //     "Equinix",
    //     "ESET",
    //     "Esri",
    //     "Etsy",
    //     "Euclid",
    //     "Eventbrite",
    //     "Evernote",
    //     "Exabeam",
    //     "Exela",
    //     "Exelon",
    //     "Exostar",
    //     "Expedia",
    //     "Expensify",
    //     "ExtraHop",
    //     "Extreme",
    //     "EY",
    //     "EZCorp",
    //     "Fabrinet",
    //     "Facebook",
    //     "FactSet",
    //     "FalconStor",
    //     "Fandango",
    //     "Fannie Mae",
    //     "Fastly",
    //     "Fidelity",
    //     "Fidelity",
    //     "FireEye",
    //     "First Data",
    //     "Fitbit",
    //     "Five9",
    //     "Flexera",
    //     "Flexport",
    //     "Foursquare",
    //     "Fox",
    //     "F5",
    //     "Freshworks",
    //     "Fuji",
    //     "Fujitsu",
    //     "Gainsight",
    //     "Galactic",
    //     "Galvanize",
    //     "GameStop",
    //     "Gartner",
    //     "Genentech",
    // }
    companies := append(arr1, arr2...)
    return companies
}

func SearchQueryTerms() []string {
    similarWords := []string{
        "layoff",
    }
    return similarWords
}